export async function seed(knex) {
  const users = await knex('users').select('auth0_id')
  return knex('songs').insert([
    {
      id: 1,
      user_id: users[0].auth0_id,
      genre: 'Indie Rock',
      title: 'Hengelo',
      artist: 'Spring Offensive',
      link: 'https://open.spotify.com/track/4rqpg85XNApASjAvqjHlb1?si=2bdc00343f3e47f2',
    },
    {
      id: 2,
      user_id: users[0].auth0_id,
      genre: 'Indie Rock',
      title: 'By Design',
      artist: 'Tigercub',
      link: 'https://open.spotify.com/track/6ICdz2wvVMDC4u801OwHA2?si=8e214d39012c4685',
    },
    {
      id: 3,
      user_id: users[0].auth0_id,
      genre: 'Jazz Metal',
      title: 'Computers',
      artist: 'Clown Core',
      link: 'https://open.spotify.com/track/6izX4jKOXNfHHIsOL7YkzF?si=c03b5e5889374a62',
    },
    {
      id: 4,
      user_id: users[0].auth0_id,
      genre: 'Funky House',
      title: 'I look to you (feat. Kimbra)',
      artist: 'Miami Horror',
      link: 'https://open.spotify.com/track/0L0GeZL4lyx34nYDzsNuG4?si=a89fdafe24d74899',
    },
    {
      id: 5,
      user_id: users[0].auth0_id,
      genre: 'Emo',
      title: 'I WIll Be Okay Everything',
      artist: 'The World Is A Beautiful Place & I Am No Longer Afraid To Die',
      link: 'https://open.spotify.com/track/6OGIl9BPa2H6UVyC0FxHM5?si=c07d49a7c1e54371',
    },
    {
      id: 6,
      user_id: users[0].auth0_id,
      genre: 'Mathcore',
      title: "You Know That Aint Them Dogs' Real Voices",
      artist: 'iwrestledabearonce',
      link: 'https://open.spotify.com/track/0NWxL0fO7j8pUSgKncipY6?si=8ed18a0ed3894793',
    },
    {
      id: 7,
      user_id: users[0].auth0_id,
      genre: 'Stoner Rock',
      title: 'Rule The Beast',
      artist: 'Torche',
      link: 'https://open.spotify.com/track/0RzryWDVHhsziHkXsT2HqV?si=b42fc552b8ff497d',
    },
    {
      id: 8,
      user_id: users[0].auth0_id,
      genre: 'Synthwave',
      title: 'From Liquid',
      artist: 'Mr Kitty',
      link: 'https://open.spotify.com/track/4jQdD7SuEB9evpBL3brmbC?si=276ce37528b94b81',
    },
    {
      id: 9,
      user_id: users[0].auth0_id,
      genre: 'Math Rock',
      title: 'Cat Fantastic',
      artist: 'TTNG',
      link: 'https://open.spotify.com/track/1kaWnMc0ryiFtPwWVKmZtb?si=aea1f12a4bdc4eef',
    },
    {
      id: 10,
      user_id: users[0].auth0_id,
      genre: 'Metal',
      title: 'Gods',
      artist: 'Sleep Token',
      is_explicit: true,
    },
    {
      id: 11,
      user_id: users[0].auth0_id,
      genre: 'Alt Rock',
      title: 'Clairvoyant',
      artist: 'BRNS',
      link: 'https://open.spotify.com/track/0XDxLlLqhuqsig4cat7aa1?si=08132d96cdae4436',
    },
    {
      id: 12,
      user_id: users[0].auth0_id,
      genre: 'Synthwave',
      title: 'Dark All Day',
      artist: 'Gunship',
      link: 'https://open.spotify.com/track/4GBJomKlZNRnODfpL299pw?si=6dc5f4da63e74507',
    },
    {
      id: 13,
      user_id: users[0].auth0_id,
      genre: 'Synthwave',
      title: 'Escape From Midwich Valley',
      artist: 'Carpenter Brut',
      link: 'https://open.spotify.com/track/1jBP9dV1MJhVcNh75yCT6I?si=6a89028c425949d3',
    },
    {
      id: 14,
      user_id: users[1].auth0_id,
      genre: 'Dance, RnB, Electronic',
      title: 'Mary Jane',
      artist: 'Rick James',
      link: 'https://open.spotify.com/track/5hWLHFSmomXmeTXEE478My?si=ae74d607f4734cc8',
    },
    {
      id: 15,
      user_id: users[1].auth0_id,
      genre: 'RnB, Soul',
      title: 'Slip Away',
      artist: 'Clarence Carter',
      link: 'https://open.spotify.com/track/7r3Hwig1mvtlVq0ZbJ09Wb?si=3975af37e0cb4911',
    },
    {
      id: 16,
      user_id: users[1].auth0_id,
      genre: 'Soul',
      title: 'Then You Can Tell Me Goodbye',
      artist: 'Bettye Swann',
      link: 'https://open.spotify.com/track/1bDjWyTOXs0sxQMC1mchSM?si=f18b79f4fc1d4215',
    },
    {
      id: 17,
      user_id: users[2].auth0_id,
      genre: 'Synth pop',
      title: 'RYDEEN',
      artist: 'Yellow Magic Orchestra',
      link: 'https://open.spotify.com/track/0RAXoT7hwOoqAXI95ryxT5?si=f99966c052614111',
    },
    {
      id: 18,
      user_id: users[2].auth0_id,
      genre: 'City Pop',
      title: "You're My Baby",
      artist: 'Hiroshi Sato',
      link: 'https://open.spotify.com/track/6zDgYObuYVCtVWnssw4myl?si=9b808dfc831d47f1',
    },
    {
      id: 19,
      user_id: users[2].auth0_id,
      genre: 'Noise',
      title: 'The Night, Assassins Night',
      artist: 'Les Rallizes Dénudés',
      link: 'https://lesrallizesdenudes.bandcamp.com/track/the-night-assassins-night',
    },
    {
      id: 20,
      user_id: users[4].auth0_id,
      genre: 'Pop',
      title: 'Jump',
      artist: 'Kris Kross',
    },
    {
      id: 21,
      user_id: users[4].auth0_id,
      genre: 'Pop',
      title: 'Remember the Time',
      artist: 'Michael Jackson',
    },
    {
      id: 22,
      user_id: users[3].auth0_id,
      genre: 'Hyperpop',
      title: 'hand crushed by a mallet',
      artist: '100 gecs',
      link: 'https://open.spotify.com/track/7CUkeiG7QtB7tPU9f8SANS?si=2ZLQwoArSgCr_bbT0haiWg',
    },
    {
      id: 23,
      user_id: users[3].auth0_id,
      genre: 'Dance, Electronic',
      title: 'Encore Une Fois - Future Breeze Edit',
      artist: 'Sash!, Future Breeze',
      link: 'https://open.spotify.com/track/3UPBOL5UtCZmJRwioMkfLD?si=kjIQ0e1_T1eDP4Sr3WHVuA',
    },
    {
      id: 24,
      user_id: users[3].auth0_id,
      genre: 'Pop',
      title: 'Hella Good',
      artist: 'No Doubt',
      link: 'https://open.spotify.com/track/6AfLmKXzhEZjwiVPs5jhdV?si=-bdgUF14TYu4TBqmTT2_gQ’',
    },
    {
      id: 25,
      user_id: users[3].auth0_id,
      genre: 'Rock',
      title: 'The Chain',
      artist: 'Fleetwood Mac',
      link: 'https://open.spotify.com/track/5e9TFTbltYBg2xThimr0rU?si=6OmZhh_ER9iFUgwTLKSxeg',
    },
    {
      id: 26,
      user_id: users[3].auth0_id,
      genre: 'Alternative Rock',
      title: 'Scar Tissue',
      artist: 'Red Hot Chili Peppers',
      link: 'https://open.spotify.com/track/1G391cbiT3v3Cywg8T7DM1?si=Zye564lgQUGJulS5qE7YGQ',
    },
    {
      id: 27,
      user_id: users[6].auth0_id,
      genre: 'Electronic',
      title: 'The Queen of All Everything',
      artist: 'OTT',
      link: 'https://www.youtube.com/watch?v=116gLvsQA4A',
    },
    {
      id: 28,
      user_id: users[6].auth0_id,
      genre: 'Electronic',
      title: 'The Lost Dream',
      artist: 'Amr Ismail',
    },
    {
      id: 29,
      user_id: users[7].auth0_id,
      genre: 'Pop',
      title: 'Are You Having Any Fun?',
      artist: 'Elaine Stritch',
      link: 'https://open.spotify.com/track/4alOnaeYVupWNmfRqdOm29?si=osBPSrp0Qe-oO9uS8HDvGA&context=spotify%3Aplaylist%3A37i9dQZF1Fa1IIVtEpGUcU',
    },
    {
      id: 30,
      user_id: users[7].auth0_id,
      genre: 'Art Rock',
      title: 'No Reptiles',
      artist: 'Everything Everything',
      link: 'https://open.spotify.com/track/1SN1gifVAKecU85lZggS8k?si=ANfle6iJSNa7XgXtvwrM0w&context=spotify%3Aplaylist%3A37i9dQZF1Fa1IIVtEpGUcU&nd=1&dlsi=91e6628bd5ae4831',
    },
    {
      id: 31,
      user_id: users[7].auth0_id,
      genre: 'Electronic',
      title: 'The Coffee Cola Song',
      artist: 'Francis Bebey',
      link: 'https://open.spotify.com/track/6qBkgf34enQ1CdaXDy46yr?si=so_rTcPmSc6ps8_qJUiHAg&nd=1&dlsi=078c8feb86e94a00',
    },
    {
      id: 32,
      user_id: users[7].auth0_id,
      genre: 'Blues',
      title: 'Iko Iko',
      artist: 'Dr. John',
      link: 'https://open.spotify.com/track/1vhlVbHnbKJPD7pqCC0cE7?si=CohqIj_MQoSMK1PszT33bw&context=spotify%3Aplaylist%3A37i9dQZF1Fa1IIVtEpGUcU',
    },
    {
      id: 33,
      user_id: users[7].auth0_id,
      genre: 'Jazz',
      title: 'The Duck - O Pate',
      artist: 'Jon Hendricks',
      link: 'https://open.spotify.com/track/1vhlVbHnbKJPD7pqCC0cE7?si=CohqIj_MQoSMK1PszT33bw&context=spotify%3Aplaylist%3A37i9dQZF1Fa1IIVtEpGUcU',
    },
    {
      id: 34,
      user_id: users[7].auth0_id,
      genre: 'Blues',
      title: 'Let the Mermaids Flirt with Me',
      artist: 'Mississippi John Hurt',
      link: 'https://open.spotify.com/track/0dLD8pwJT8hXSB41XUocaR?si=2khdPkJjTbq6XfpI6AKMYQ&nd=1&dlsi=5ebc0ef36d004e8a',
    },
  ])
}
